name: "Release package"
on: push

jobs:
  release_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: "npm ci"
        run: npm ci

      - name: "npx semantic-release"
        run: npx semantic-release --allow-same-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
